### ISSUE TITLE
Refactor test cases to run from root directory

### ISSUE THREAD

**Issue by alexjps1** [uoclass/tstat#20]
Currently, test cases only run properly if run from the root directory, like so:
`python3 unit-testing/unittests.py`

This should be fixed so that `unittests.py` can be run from the `unit-testing` directory, for better compatibility with debugging features in IDEs, which will run the file from the directory in which it resides.

**Comment by alexjps1** [comment]
I can do you one better. Now tests can be run from any directory without problems. This also makes the PyCharm automatic running of unit tests (green arrow icon) work as it should.

e744cb51b2e9a174bbfc54125b33974e7639f40f

**Comment by ericedwards02** [comment]
Let's Get This Money!
